# Generated by Django 5.2 on 2025-04-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_alter_message_options_and_more"),
        ("selfcheck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_role",
            field=models.CharField(
                choices=[("doctor", "의사"), ("nurse", "간호사")],
                default="nurse",
                max_length=10,
            ),
        ),
    ]
