# Generated by Django 5.2 on 2025-04-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_message_selfcheck_message_sender_role"),
        ("selfcheck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="selfcheck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="selfcheck.selfcheck",
            ),
        ),
    ]
