# Generated by Django 5.2 on 2025-04-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_message_selfcheck"),
        ("patients", "0002_alter_patient_patient_id_devicetoken"),
        ("selfcheck", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="selfcheck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="selfcheck.selfcheck",
            ),
        ),
    ]
