# Generated by Django 5.1.7 on 2025-05-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_message_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sender_role",
        ),
    ]
