# Generated by Django 5.1.7 on 2025-05-04 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_user"),
        ("selfcheck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfcheck",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selfchecks",
                to="patients.patient",
            ),
        ),
    ]
