# Generated by Django 5.2 on 2025-05-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_file', models.FileField(upload_to='ct_scans/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_scans', to='patients.patient')),
            ],
        ),
    ]
