# Generated by Django 5.2 on 2025-05-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_ctscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctscan',
            name='study_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
