# Generated by Django 5.2 on 2025-04-18 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic_bp", models.IntegerField(verbose_name="수축기 혈압")),
                ("diastolic_bp", models.IntegerField(verbose_name="이완기 혈압")),
                ("pulse", models.IntegerField(verbose_name="맥박")),
                ("respiration_rate", models.IntegerField(verbose_name="호흡수")),
                ("temperature", models.FloatField(verbose_name="체온")),
                ("oxygen", models.FloatField(verbose_name="산소포화도 (%)")),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
