# Generated by Django 5.2 on 2025-04-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headache", models.BooleanField()),
                ("dizziness", models.BooleanField()),
                ("numbness", models.BooleanField()),
                ("speech_difficulty", models.BooleanField()),
                ("vision_blur", models.BooleanField()),
                ("nausea", models.BooleanField()),
                ("pain_location", models.CharField()),
                ("pain_score", models.IntegerField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "좋음"),
                            ("anxious", "불안"),
                            ("depressed", "우울"),
                        ],
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
