# Generated by Django 5.2 on 2025-04-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfcheck',
            name='pain_location',
            field=models.CharField(max_length=100),
        ),
    ]
