# Generated by Django 5.1.7 on 2025-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("doctor", "의사"), ("nurse", "간호사"), ("patient", "환자")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
